### ISSUE TITLE
Which file contains NABERT+?

### ISSUE THREAD

**Issue by WSTC2007** [raylin1000/drop_bert#1]
Hello~
I want to ask a question: Which file contains NABERT+ model in the drop_bert folder?

**Comment by raylin1000** [comment]
All the files with `old` at the end are ones we kept only for backwards compatibility with some of our older trained models when we were experimenting, so those files might not be potentially particularly useful. `augmented_bert.py` contains the NABERT base model, `augmented_bert_plus.py` contains the NABERT+ model with only standard numbers, and `augmented_bert_templated.py` contains the full NABERT+ model (with standard numbers as well as templating). I'll update the README to make things more clear.
