### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by WSTC2007** [raylin1000/drop_bert#3]
In the augmented_bert.py, model.register('nabber_old'), but in the augmented_bert_old.py, model.register('nabert'). Which one is nabert model? 
By the way, can you tell me the correspondence between the configuration file and the model file? thx!

**Comment by raylin1000** [comment]
I'll cleanup the models and configs shortly to make things more clear.

**Comment by WSTC2007** [comment]
> I'll cleanup the models and configs shortly to make things more clear.

Thank you very much.
